In [2]:
from binance.client import Client
import pandas as pd

ModuleNotFoundError: No module named 'binance'

In [1]:
client = Client()

# -- You can change the crypto pair ,the start date and the time interval below --
pairName = "BTCUSDT"
startDate = "01 january 2021"
timeInterval = Client.KLINE_INTERVAL_1HOUR

# -- Load all price data from binance API --
klinesT = client.get_historical_klines(pairName, timeInterval, startDate)

# -- Define your dataset --
df = pd.DataFrame(klinesT, columns = ['timestamp', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_av', 'trades', 'tb_base_av', 'tb_quote_av', 'ignore' ])
df['close'] = pd.to_numeric(df['close'])
df['high'] = pd.to_numeric(df['high'])
df['low'] = pd.to_numeric(df['low'])
df['open'] = pd.to_numeric(df['open'])

# -- Set the date to index --
df = df.set_index(df['timestamp'])
df.index = pd.to_datetime(df.index, unit='ms')
del df['timestamp']

print("Data loaded 100%")
df

NameError: name 'Client' is not defined

In [8]:
import pandas as pd
import ccxt

def get_historical_from_db(exchange, symbol, timeframe, path="database/"):
    symbol = symbol.replace('/','-')
    df = pd.read_csv(filepath_or_buffer=path+str(exchange.name)+"/"+timeframe+"/"+symbol+".csv")
    df = df.set_index(df['date'])
    df.index = pd.to_datetime(df.index, unit='ms')
    del df['date']
    return df

get_historical_from_db(ccxt.binance(), "BTC/USDT", "1h", path="./database/")

                         open      high       low     close       volume
date
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83    47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32    23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35     7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99     4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69     0.972807
...                       ...       ...       ...       ...          ...
2022-03-07 10:00:00  38152.19  38290.00  37972.71  38018.91  1662.532640
2022-03-07 11:00:00  38018.90  38399.54  37970.73  38337.05  1504.323710
2022-03-07 12:00:00  38337.05  38765.16  38337.05  38596.21  2760.179560
2022-03-07 13:00:00  38596.22  39183.49  38531.20  39025.77  3248.385390
2022-03-07 14:00:00  39025.78  39285.00  38909.30  39116.24  1061.168710

[39797 rows x 5 columns]